### ISSUE TITLE
Using this tool on dozens of bacterial genome assemblies

### ISSUE THREAD

**Issue by slvrshot** [meren/reads-for-assembly#3]
Hi I searched around for a tool that could simulate reads and stumbled on this. I have some sequences generated on MiSeq or HiSeq. There are roughly 100 assembled genomes....unfortunately I don't know where the original paired-end reads are as I didn't sequence these samples. I figured I could try simulating reads but it seems your tool isn't really designed for dozens of samples or am I wrong? Thanks for creating this tool!

**Comment by slvrshot** [comment]
Also what method would you suggest for creating a config file with hundreds of isolates? I want to process each genome assembly with the paired end reads script and name the paired end reads the same as the original genome assembly.

**Comment by meren** [comment]
> I figured I could try simulating reads but it seems your tool isn't really designed for dozens of samples or am I wrong?

While it is not particularly designed/tested for that, I don't see why it shouldn't work. It may take a bit of time to run though.

> Also what method would you suggest for creating a config file with hundreds of isolates? 

I am sorry to not be able to make a good suggestion for this.


Best,
